### PR TITLE
Added osx and linux to travis

### PR DESCRIPTION
**Pull request by nmmsv**

### CODE REVIEW

**Comment by gymreklab** [comment]
Thanks for the PR. This looks reasonable. But the merge check says checks are failing travis. I will wait to merge until that is resolved. Do you know what is causing the errors?

**Comment by nmmsv** [comment]
I'm still working on this, please don't merge yet! Travis doesn't natively support testing python on osx, so I have to do some trickery! I think I'm almost there tho. I will merge it once everything worked.

**Comment by nmmsv** [comment]
@LiterallyUniqueLogin do you mind taking a look at this before merging the other PR? If you think it looks ok I'll merge. I'm worried working on both PRs at the same time may cause merge conflicts.

**Comment by LiterallyUniqueLogin** [comment]
I pinged you on slack a while back with my (few) comments - would you
rather I relay those comments elsewhere?

**Comment by LiterallyUniqueLogin** [comment]
Why the TOXENV in the commit?

I don't see you using tox anywhere, but maybe I'm missing it.

**Pull request merged**
