### PR TITLE
fix: vcf input via stdin

### PR DESCRIPTION
**Pull request by aryarm**
allows `trtools` to accept piped VCFs or VCFs that are specified via process substitution

Previously, the user would simply receive this error message, instead:
> Could not find VCF file

### CODE REVIEW

**Comment by aryarm** [comment]
@aarushi03 does this help with the issue you were having?

**Comment by LiterallyUniqueLogin** [comment]
This seems fine. I don't know if it actually does what it intends to (there are no tests regarding standard in, and I haven't dug enough to check for myself), but the new test is good and I can't see this breaking anything a user is likely to run into.

**Comment by aryarm** [comment]
Thanks for the review!

I tried to create a test with stdin and wasn't able to. I just don't know how to do that in a way that allows `cyvcf2` to read from it

My only external validation that we have that this works is that @aarushi03 manually checked it

**Comment by aryarm** [comment]
Thanks for the review!

I tried to create a test with stdin and wasn't able to. I just don't know how to do that in a way that allows `cyvcf2` to read from it

My only external validation that we have that this works is that @aarushi03 manually checked it

**Pull request merged**
